name: copilot-deploy-environment

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      WEBAPI_ARTIFACT_NAME:
        required: true
        type: string
      MEMORYPIPELINE_ARTIFACT_NAME:
        required: true
        type: string
      PLUGINS_ARTIFACT_NAME:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID: 
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_OPENAI_ENDPOINT:
        required: true
      AZUREOPENAI__NAME:
        required: true
      CC_DEPLOYMENT_NAME:
        required: true
      CC_DEPLOYMENT_GROUP_NAME:
        required: true
      CC_DEPLOYMENT_REGION:
        required: true
      APPLICATION_CLIENT_ID:
        required: true
      AZURE_INSTANCE:
        required: true
    outputs:
      backend-host:
        description: "Host on which backend runs"
        value: ${{jobs.deploy-backend.outputs.backend-host}}

permissions:
  contents: read
  id-token: write

jobs:
  deploy-infra:
    uses: ./.github/workflows/copilot-deploy-infra.yml
    with:
      ENVIRONMENT: ${{inputs.ENVIRONMENT}}
    secrets: inherit

  deploy-backend:
    needs: [deploy-infra]
    uses: ./.github/workflows/copilot-deploy-backend.yml
    with:
      ARTIFACT_NAME: ${{inputs.WEBAPI_ARTIFACT_NAME}}
      DEPLOYMENT_NAME: ${{needs.deploy-infra.outputs.deployment-id}}
      ENVIRONMENT: ${{inputs.ENVIRONMENT}}
    secrets: inherit

  deploy-memorypipeline:
    needs: [deploy-infra]
    uses: ./.github/workflows/copilot-deploy-memorypipeline.yml
    with:
      ARTIFACT_NAME: ${{inputs.MEMORYPIPELINE_ARTIFACT_NAME}}
      DEPLOYMENT_NAME: ${{needs.deploy-infra.outputs.deployment-id}}
      ENVIRONMENT: ${{inputs.ENVIRONMENT}}
    secrets: inherit