name: copilot-deploy-environment

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      WEBAPI_ARTIFACT_NAME:
        required: true
        type: string
      MEMORYPIPELINE_ARTIFACT_NAME:
        required: true
        type: string
      PLUGINS_ARTIFACT_NAME:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_OPENAI_ENDPOINT:
        required: true
    outputs:
      backend-host:
        description: "Host on which backend runs"
        value: ${{jobs.deploy-backend.outputs.backend-host}}

permissions:
  contents: read
  id-token: write

jobs:
  deploy-infra:
    uses: ./.github/workflows/copilot-deploy-infra.yml
    with:
      ENVIRONMENT: ${{inputs.ENVIRONMENT}}
    secrets:
      AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      AZURE_OPENAI_ENDPOINT: ${{secrets.AZURE_OPENAI_ENDPOINT}}      
      AZUREOPENAI__NAME: ${{secrets.AZUREOPENAI__NAME}}
      CC_DEPLOYMENT_NAME: ${{secrets.CC_DEPLOYMENT_NAME}}
      CC_DEPLOYMENT_GROUP_NAME: ${{secrets.CC_DEPLOYMENT_GROUP_NAME}}
      CC_DEPLOYMENT_REGION: ${{secrets.CC_DEPLOYMENT_REGION}}
      APPLICATION_CLIENT_ID: ${{secrets.APPLICATION_CLIENT_ID}}
      AZURE_INSTANCE: ${{secrets.AZURE_INSTANCE}}

  deploy-backend:
    needs: [deploy-infra]
    uses: ./.github/workflows/copilot-deploy-backend.yml
    with:
      ARTIFACT_NAME: ${{inputs.WEBAPI_ARTIFACT_NAME}}
      DEPLOYMENT_NAME: ${{needs.deploy-infra.outputs.deployment-id}}
      ENVIRONMENT: ${{inputs.ENVIRONMENT}}
    secrets:
      AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      CC_DEPLOYMENT_GROUP_NAME: ${{secrets.CC_DEPLOYMENT_GROUP_NAME}}

  deploy-memorypipeline:
    needs: [deploy-infra]
    uses: ./.github/workflows/copilot-deploy-memorypipeline.yml
    with:
      ARTIFACT_NAME: ${{inputs.MEMORYPIPELINE_ARTIFACT_NAME}}
      DEPLOYMENT_NAME: ${{needs.deploy-infra.outputs.deployment-id}}
      ENVIRONMENT: ${{inputs.ENVIRONMENT}}
    secrets:
      AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      CC_DEPLOYMENT_GROUP_NAME: ${{secrets.CC_DEPLOYMENT_GROUP_NAME}}