name: copilot-deploy-pipeline

on:
  workflow_dispatch:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  build-webapi:
    uses: ./.github/workflows/copilot-build-backend.yml

  build-memorypipeline:
    uses: ./.github/workflows/copilot-build-memorypipeline.yml

  # build-plugins:
  #   uses: ./.github/workflows/copilot-build-plugins.yml

  int:
    needs: [build-webapi, build-memorypipeline]
    uses: ./.github/workflows/copilot-deploy-environment.yml
    with:
      ENVIRONMENT: int
      WEBAPI_ARTIFACT_NAME: ${{needs.build-webapi.outputs.artifact}}
      MEMORYPIPELINE_ARTIFACT_NAME: ${{needs.build-memorypipeline.outputs.artifact}}
      PLUGINS_ARTIFACT_NAME: ${{needs.build-plugins.outputs.artifact}}
    secrets: inherit

  # int-tests:
  #   needs: [int]
  #   uses: ./.github/workflows/copilot-run-integration-tests.yml
  #   with:
  #     ENVIRONMENT: int
  #     BACKEND_HOST: ${{needs.int.outputs.backend-host}}
